config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "products#index"
  resources :products

  # basket 
  get "basket", to: "basket#index"
  post "basket", to: "basket#create"
  delete "basket", to: "basket#destroy"
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/product.rb
class Product < ApplicationRecord
  scope :in_stock, -> { where("quantity_in_stock > 0") }

  monetize :cost_cents
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# Add a nice comment here once your app has taken shape!
class ApplicationController < ActionController::Base
end

app/controllers/basket_controller.rb
class BasketController < ApplicationController
  def index
    @basket_items = Product.where(id: session[:basket_items].keys)
  end

  def create
    @product = Product.find params[:id]

    if session[:basket_items][params[:id]].present?
      session[:basket_items][params[:id]]["quantity"] += 1 
    else
      session[:basket_items][params[:id]] = { "quantity" => 1 }
    end

    update_item_counters
  end

  def destroy
    @product = Product.find params[:id]

    if session[:basket_items].present? && 
      session[:basket_items][params[:id]].present? && 
      session[:basket_items][params[:id]]["quantity"] > 1
      session[:basket_items][params[:id]]["quantity"] -= 1
    else
      session[:basket_items].delete(params[:id])
    end

    update_item_counters
  end

  private

  def update_item_counters
    render turbo_stream: [
      turbo_stream.update("basket_items_counter", partial: "shared/basket"),
      turbo_stream.update("product_#{params[:id]}", partial: "basket/item_breakdown", locals: { product: @product }),
      turbo_stream.update("basket_total", partial: "basket/total")
    ]
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.in_stock
  end

  def show
    @product = Product.find params[:id]
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# The application level helper, where you can put heleprs that will be globally
# accessible to your app.
module ApplicationHelper
end

app/helpers/basket_helper.rb
module BasketHelper
  def basket_items
    session[:basket_items] ||= {}
  end

  def basket_item_count(product_id)
    session[:basket_items][product_id.to_s].present? ? session[:basket_items][product_id.to_s]["quantity"] : 0
  end

  def basket_item_subtotal(product_id)
    product_id = product_id.to_s
    product = Product.find product_id
    if product && session[:basket_items][product_id].present?
      product.cost * session[:basket_items][product_id]["quantity"]
    else
      Money.new(0)
    end
  end

  def basket_total_cost
    session[:basket_items].keys.reduce(Money.new(0)) { |total, product_id| total += basket_item_subtotal(product_id) }
  end
end

app/views/basket/_controls.html.erb
<div style="display: flex; margin: auto auto; justify-content: space-evenly; width: 250px;">
  <p style="margin-top: 15px;">Quantity:</p>
  <%= button_to basket_path(id: product.id), method: :delete do %>
    <div>
      <p>- 1</p>
    </div>
  <% end %>

  <p><%= basket_item_count(product.id) %></p>

  <%= button_to basket_path(id: product.id) do %>
    <div>
      <p>+ 1</p>
    </div>
  <% end %>
</div>

app/views/basket/_item_breakdown.html.erb
<%= render partial: "products/product", locals: { product: product } %>
<%= render partial: "controls", locals: { product: product } %>
<%= render partial: "subtotal", locals: { product: product } %>

app/views/basket/_subtotal.html.erb
<div style="display: flex; margin: auto auto; justify-content: space-evenly; width: 250px;">
  <p>Item subtotal:</p>
  <p><%= basket_item_subtotal(product.id).format(no_cents_if_whole: true) %></p>
</div>

app/views/basket/_total.html.erb
<div style="display: flex">
  <p>Basket Total:</p>
  <p style="margin-left: 20px;"><%= basket_total_cost.format(no_cents_if_whole: true) %></p>
</div>

app/views/basket/index.html.erb
<div style="display: flex; flex-direction: column; margin: auto auto; margin-top: 30px;">
  <% if @basket_items.any? %>
    <% @basket_items.each do |product| %>
      <%= turbo_frame_tag dom_id(product) do %>
        <%= render partial: "item_breakdown", locals: { product: product } %>
      <% end %>
    <% end %>
    <div style="display: flex; flex-direction: row; justify-content: space-evenly; width: 100%; border-top: 1px solid gray;">
      <%= turbo_frame_tag "basket_total" do %>
        <%= render partial: "total" %>
      <% end %>
    </div>

    <button>Checkout</button>
  <% else %>
    <h3>Basket is empty</h3>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RubyCodingExercise</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Abel&display=swap" rel="stylesheet"> 

    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body style="display: flex; flex-direction: column; font-family: 'Abel', sans-serif;">
    <%= render "shared/header" %>
    <%= yield %>
  </body>
</html>

app/views/products/_product.html.erb
<%= link_to product_path(product) do %>
  <div style="display: flex; flex-direction: row; margin-top: 20px;">
    <img src="https://picsum.photos/150?v=<%= product.id %>">
    <div style="flex-direction: column; margin-left: 30px;">
      <h3><%= product.title %></h3>
      <p><%= product.description %></p>
      <p><%= product.cost.format(no_cents_if_whole: true) %></p>
    </div>
  </div>
<% end %>

app/views/products/index.html.erb
<div style="display: flex; flex-direction: column; margin: auto auto; margin-top: 30px;">
  <% @products.each do |product| %>
    <%= render partial: "product", locals: { product: product } %>
  <% end %>
</div>

app/views/products/show.html.erb
<div style="display: flex; flex-direction: row; margin: auto auto; margin-top: 30px;">
  <img src="https://picsum.photos/150?v=<%= @product.id %>">
  <div style="flex-direction: column; margin-left: 30px;">
    <h3 id="title"><%= @product.title %></h3>
    <p><%= @product.description %></p>
    <p><%= @product.additional_details %></p>
    <p><%= @product.cost.format(no_cents_if_whole: true) %></p>

    <%= button_to basket_path(id: @product.id), html: { id: "add_to_basket" } do %>
      <p>Add to Basket</p>
    <% end %>
  </div>
</div>

app/views/shared/_basket.html.erb
<%= link_to basket_path do %>
  <div style="display: flex;">
    <p id="basket_item_count"><%= basket_items.keys.size %></p>
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" style="height: 25px; width: 25px; margin: auto auto; margin-left: 10px;">
      <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 10.5V6a3.75 3.75 0 10-7.5 0v4.5m11.356-1.993l1.263 12c.07.665-.45 1.243-1.119 1.243H4.25a1.125 1.125 0 01-1.12-1.243l1.264-12A1.125 1.125 0 015.513 7.5h12.974c.576 0 1.059.435 1.119 1.007zM8.625 10.5a.375.375 0 11-.75 0 .375.375 0 01.75 0zm7.5 0a.375.375 0 11-.75 0 .375.375 0 01.75 0z" />
    </svg>
  </div>
<% end %>

app/views/shared/_header.html.erb
<div style="display: flex; padding: 1rem; border-bottom: 2px solid grey; justify-content: space-evenly;">
  <div style="width: 100px;"></div>
  <%= link_to products_path do %>
    <h1 style="margin: auto auto;">The Music Shop</h1>
  <% end %>

  <%= turbo_frame_tag "basket_items_counter" do %>
    <%= render partial: "shared/basket" %>
  <% end %>
</div>